### ISSUE TITLE
Forced signed out

### ISSUE THREAD

**Issue by quthla** [dani-garcia/bitwarden_rs#275]
I am using bitwarden_rs for some days now but I noticed I am signed out frequently. It happened on the mobile but but also the browser extension. I need to login again then.

This never happened using the official implementation. Is there any reason you could think of causing this?

I run bitwarden_rs on my server on port 444 because it's not yet possible to reverse proxy it to a directory. The container was not restarted.

**Comment by dani-garcia** [comment]
Interesting, I only use the web vault, so I haven't noticed this. The authentication tokens are set to expire in two hours, but we also send a refresh token that doesn't expire and would allow the clients to get another authentication token without asking for the password. For contrast, the official vault sends tokens that expire after an hour, so it should work the same.

Do you have two factor authentication enabled?

**Comment by pew** [comment]
I have this issue as well and I think it's related to [this issue here](https://github.com/bitwarden/mobile/issues/325). I haven't had the chance to play around with this error code rewriting yet, I also don't think it's the best solution.

**Comment by quthla** [comment]
I don't use 2FA and there's nothing unusual in the logs. Unfortunately logs are not timestamped or else I could look for requests around a particular time. 

But the server should never be not available I think.

**Comment by quthla** [comment]
Logged in few hours ago on the ios app, now logged out again :/

**Comment by mprasil** [comment]
Are you using iOS or Android? I've noticed the forced logout once, but unfortunately wasn't able to troubleshoot it just there. But generally speaking bar that one instance it never happened to me on Android. (I still do have to enter the password, but that's because I don't want to store the master password on device)

**Comment by pew** [comment]
@mprasil I'm on iOS 12.1/bitwarden 1.20.0

**Comment by quthla** [comment]
I'm on ios too but it also happened once with the Firefox extension. There's something in the log saying not implemented. Maybe that's the cause 

Will post it later

**Comment by dani-garcia** [comment]
I updated the beta branch with some changes to implement that method and return a similar result to the official server. I'd appreciate if you tested it to see if that solves the issue.

(If you are using the docker hub image, you'll have to wait for @mprasil to trigger the build)

**Comment by mprasil** [comment]
I've now triggered the [build](https://hub.docker.com/r/mprasil/bitwarden/builds/barzqczgwodewsddql2eg9s/), will take about an hour.

I've also experienced some logouts in the mobile app today and that was also the only error message I could see. I start to think that it is some client change, that is slowly rolled out, so I'm only hitting the issue now as my app was updated. Perhaps it was earlier on iPhones?

@dani-garcia, I see there was schema change between master and this beta branch, but it seems to be simple enough that switching between versions should be OK right?

**Comment by dani-garcia** [comment]
It's just a column for the new attachment keys, as long as you don't upload an attachment in the beta version (or convert an old attachment to the new format) it should be fine to move between the two of them. If you do that, then they won't be able to be read from the old version anymore.

Anyway, according to https://rocket.rs/v0.4/news/2018-11-30-version-0.4-rc-2/ the final version of rocket should have been released yesterday, so once it's done -and it'll probably be soon-, this branch is going to be merged in without any major changes, so it can be considered pretty stable. 

Still, I would heavily recommend to do a database backup when updating versions just in case.

**Comment by quthla** [comment]
Could you maybe timestamp the logs? Should be easier then to track down issues

**Comment by mprasil** [comment]
@quthla how do you check the logs? If it's via `docker logs`, you can use `-t` to show timestamp.

**Comment by dani-garcia** [comment]
I made another change to the beta version, switching to another logging system. Now there are timestamps and log file and syslog support. So you can use that too.

**Comment by mprasil** [comment]
I've triggered [another build](https://hub.docker.com/r/mprasil/bitwarden/builds/b42wrpqrh2x7cqm2ke23shh/) with latest changes.

Just one note on the extended logging, can we set it to false as default? When users run the server via docker, docker provides its own timestamps. When you run it via some init system like systemd, it also provides its own timestamps.

**Comment by dani-garcia** [comment]
I feel like it would be a better idea to have it enabled by default, and to explicitly change it in the dockerfile / systemd config file.
Basically, set `ENV EXTENDED_LOGGING=false` in the dockerfiles, and configure the systemd service in the same way (which would only be done once). That way everyone gets the best option posible with the least amount of work. What do you think?

**Comment by mprasil** [comment]
I'd say if the logs go to stdout, they are either not preserved or they are preserved with timestamp. So maybe we could do extended logs automatically when logging to file is set.

Having that said many servers do log with timestamp just because it was common in the past that the logs were redirected to a file from stdout or whatever was collecting them just stored the lines, so it does look stupid now having the time info twice, but it's just few bytes extra and better to have that info twice than to miss it once. :smile: 

The only drawback is that we're probably breaking the fail2ban setup some users might have. But I guess that's okay as it will be part of release notes or something.

**Comment by mprasil** [comment]
I'm not really using attachments, so I went ahead and tested the latest beta version. So far all looks OK, no forced log out yet. But that's probably too early to judge. Functionally I didn't spot any major breakage.

**Comment by TMHBOFH** [comment]
Hi,
i test beta release and get with the android app the following error messages.

[2018-12-07][06:52:32][rocket::rocket][INFO] POST /api/accounts/prelogin application/json; charset=utf-8:
[2018-12-07][06:52:32][_][INFO] Matched: POST /api/accounts/prelogin (prelogin)
[2018-12-07][06:52:32][_][INFO] Outcome: Success
[2018-12-07][06:52:32][_][INFO] Response succeeded.
[2018-12-07][06:52:32][rocket::rocket][INFO] POST /identity/connect/token application/x-www-form-urlencoded:
[2018-12-07][06:52:32][_][INFO] Matched: POST /identity/connect/token (login)
[2018-12-07][06:52:32][bitwarden_rs::api::identity][ERROR] device_identifier cannot be blank
[2018-12-07][06:52:32][_][INFO] Outcome: Success
[2018-12-07][06:52:32][_][INFO] Response succeeded.


How can i help to find the problem.

**Comment by mprasil** [comment]
FYI: I've renamed the image to `mprasil/bitwarden:beta` as there are much more changes than just rocket update. The [build](https://hub.docker.com/r/mprasil/bitwarden/builds/bbffdverzjusdq3faz5x4rw/) is now running.

**Comment by dani-garcia** [comment]
@TMHBOFH I made the device_identifier optional in the latest commit just now. It should work fine now.

**Comment by quthla** [comment]
@dani-garcia Upgraded to beta. Uploading / viewing attachments in browser working. I can see the attachment from the iOS app but can neither download nor upload attachments

**Comment by quthla** [comment]
Just added `DOMAIN`, started container up, was logged out in iOS app again. Are the access tokens stored in memory only?

```
[2018-12-07][18:29:12][rocket::rocket][INFO] GET /api/accounts/revision-date application/json:
[2018-12-07][18:29:12][_][INFO] Matched: GET /api/accounts/revision-date (revision_date)
[2018-12-07][18:29:12][bitwarden_rs::auth][ERROR] Error validating jwt - Error(
    InvalidIssuer
)
[2018-12-07][18:29:12][bitwarden_rs::auth][ERROR] Invalid claim
[2018-12-07][18:29:12][_][INFO] Outcome: Failure
[2018-12-07][18:29:12][_][WARN] Responding with 401 Unauthorized catcher.
[2018-12-07][18:29:12][_][INFO] Response succeeded.
[2018-12-07][18:29:13][rocket::rocket][INFO] PUT /api/devices/identifier/xyz/clear-token:
[2018-12-07][18:29:13][_][INFO] Matched: PUT /api/devices/identifier/<uuid>/clear-token (clear_device_token)
[2018-12-07][18:29:13][bitwarden_rs::auth][ERROR] No access token provided
[2018-12-07][18:29:13][_][INFO] Outcome: Failure
[2018-12-07][18:29:13][_][WARN] Responding with 401 Unauthorized catcher.
[2018-12-07][18:29:13][_][INFO] Response succeeded.
```

**Comment by dani-garcia** [comment]
The jwt tokens have the domain in them, so when changing it they become invalid. If you log out and log in again it should work.

The No access token provided error after the clear-token is fixed in the latest commit, but you'll have to wait until @mprasil builds a new image.

**Comment by i-ghost** [comment]
I'm getting the "No access token provided" error as above on a new install, trying to log in to a newly registered admin account. I'm immediately logged out when I sign in. Using the latest `beta` tag doesn't seem to fix this.

**Comment by dani-garcia** [comment]
Can you provide logs? Also, what devices are you using to connect?

**Comment by i-ghost** [comment]
Of course, here are the logs.

The setup is reverse proxied by nginx according to the example provided in PROXY.md.

I have tried from Chrome desktop, and using the official BitWarden app on iOS.

```[2018-12-08][17:01:32][rocket::rocket][INFO] GET / text/html:
[2018-12-08][17:01:32][_][INFO] Matched: GET / (web_index)
[2018-12-08][17:01:32][_][INFO] Outcome: Success
[2018-12-08][17:01:32][_][INFO] Response succeeded.
[2018-12-08][17:01:32][rocket::rocket][INFO] GET /app/main.252d46106ad388896181.css text/css:
[2018-12-08][17:01:32][_][INFO] Matched: GET /<p..> (web_files)
[2018-12-08][17:01:32][_][INFO] Outcome: Success
[2018-12-08][17:01:32][_][INFO] Response succeeded.
[2018-12-08][17:01:32][rocket::rocket][INFO] GET /images/logo-dark@2x.png image/webp:
[2018-12-08][17:01:32][_][INFO] Matched: GET /<p..> (web_files)
[2018-12-08][17:01:32][_][INFO] Outcome: Success
[2018-12-08][17:01:32][_][INFO] Response succeeded.
[2018-12-08][17:01:32][rocket::rocket][INFO] GET /app/polyfills.252d46106ad388896181.js:
[2018-12-08][17:01:32][_][INFO] Matched: GET /<p..> (web_files)
[2018-12-08][17:01:32][_][INFO] Outcome: Success
[2018-12-08][17:01:32][_][INFO] Response succeeded.
[2018-12-08][17:01:32][rocket::rocket][INFO] GET /app/vendor.252d46106ad388896181.js:
[2018-12-08][17:01:32][_][INFO] Matched: GET /<p..> (web_files)
[2018-12-08][17:01:32][_][INFO] Outcome: Success
[2018-12-08][17:01:32][rocket::rocket][INFO] GET /app/main.252d46106ad388896181.js:
[2018-12-08][17:01:32][_][INFO] Matched: GET /<p..> (web_files)
[2018-12-08][17:01:32][_][INFO] Outcome: Success
[2018-12-08][17:01:32][_][INFO] Response succeeded.
[2018-12-08][17:01:32][rocket::rocket][INFO] GET /fonts/fontawesome-webfont.woff2:
[2018-12-08][17:01:32][_][INFO] Matched: GET /<p..> (web_files)
[2018-12-08][17:01:32][_][INFO] Outcome: Success
[2018-12-08][17:01:32][_][INFO] Response succeeded.
[2018-12-08][17:01:32][rocket::rocket][INFO] GET /fonts/Open_Sans-normal-400.woff:
[2018-12-08][17:01:32][_][INFO] Matched: GET /<p..> (web_files)
[2018-12-08][17:01:32][_][INFO] Outcome: Success
[2018-12-08][17:01:32][_][INFO] Response succeeded.
[2018-12-08][17:01:32][_][INFO] Response succeeded.
[2018-12-08][17:01:33][rocket::rocket][INFO] GET /locales/en/messages.json?cache=xggkft:
[2018-12-08][17:01:33][_][INFO] Matched: GET /<p..> (web_files)
[2018-12-08][17:01:33][_][INFO] Outcome: Success
[2018-12-08][17:01:33][_][INFO] Response succeeded.
[2018-12-08][17:01:33][rocket::rocket][INFO] GET /fonts/Open_Sans-normal-600.woff:
[2018-12-08][17:01:33][_][INFO] Matched: GET /<p..> (web_files)
[2018-12-08][17:01:33][_][INFO] Outcome: Success
[2018-12-08][17:01:33][_][INFO] Response succeeded.
[2018-12-08][17:01:33][rocket::rocket][INFO] GET /manifest.json:
[2018-12-08][17:01:33][_][INFO] Matched: GET /<p..> (web_files)
[2018-12-08][17:01:33][_][INFO] Outcome: Success
[2018-12-08][17:01:33][_][INFO] Response succeeded.
[2018-12-08][17:01:44][rocket::rocket][INFO] POST /api/accounts/prelogin application/json; charset=utf-8:
[2018-12-08][17:01:44][_][INFO] Matched: POST /api/accounts/prelogin (prelogin)
[2018-12-08][17:01:44][_][INFO] Outcome: Success
[2018-12-08][17:01:44][_][INFO] Response succeeded.
[2018-12-08][17:01:44][rocket::rocket][INFO] POST /identity/connect/token application/x-www-form-urlencoded; charset=utf-8:
[2018-12-08][17:01:44][_][INFO] Matched: POST /identity/connect/token (login)
[2018-12-08][17:01:44][_][INFO] Outcome: Success
[2018-12-08][17:01:44][_][INFO] Response succeeded.
[2018-12-08][17:01:44][rocket::rocket][INFO] POST /notifications/hub/negotiate text/plain; charset=UTF-8:
[2018-12-08][17:01:44][_][INFO] Matched: POST /notifications/hub/negotiate (negotiate)
[2018-12-08][17:01:44][_][INFO] Outcome: Success
[2018-12-08][17:01:44][_][INFO] Response succeeded.
[2018-12-08][17:01:44][rocket::rocket][INFO] GET /fonts/Open_Sans-normal-700.woff:
[2018-12-08][17:01:44][_][INFO] Matched: GET /<p..> (web_files)
[2018-12-08][17:01:44][_][INFO] Outcome: Success
[2018-12-08][17:01:44][_][INFO] Response succeeded.
[2018-12-08][17:01:44][rocket::rocket][INFO] GET /api/sync?excludeDomains=true application/json:
[2018-12-08][17:01:44][_][INFO] Matched: GET /api/sync?<data..> (sync)
[2018-12-08][17:01:44][bitwarden_rs::auth][ERROR] No access token provided
[2018-12-08][17:01:44][_][INFO] Outcome: Failure
[2018-12-08][17:01:44][_][WARN] Responding with 401 Unauthorized catcher.
[2018-12-08][17:01:44][_][INFO] Response succeeded.
```

**Update:** Ok - so it turns out it was a bad nginx site config - my generic shared config full of `proxy_` directives wasn't playing well with BitWarden - excluding it seems to have resolved this. After some further testing, it turns out that setting `proxy_set_header Authorization <value>;` will cause issues.

**Comment by quthla** [comment]
Once again logged out on iOS unfortunately. 

```
[2018-12-09][00:00:41][rocket::rocket][INFO] POST /identity/connect/token application/x-www-form-urlencoded:
[2018-12-09][00:00:41][_][INFO] Matched: POST /identity/connect/token (login)
[2018-12-09][00:00:41][rocket::rocket][INFO] POST /identity/connect/token application/x-www-form-urlencoded:
[2018-12-09][00:00:41][_][INFO] Matched: POST /identity/connect/token (login)
[2018-12-09][00:00:41][bitwarden_rs::api::identity][ERROR] Failed to add device to user
[2018-12-09][00:00:41][_][INFO] Outcome: Success
[2018-12-09][00:00:41][_][INFO] Response succeeded.
[2018-12-09][00:00:41][_][INFO] Outcome: Success
[2018-12-09][00:00:41][_][INFO] Response succeeded.
[2018-12-09][00:00:41][rocket::rocket][INFO] PUT /api/devices/identifier/abc/clear-token:
[2018-12-09][00:00:41][_][INFO] Matched: PUT /api/devices/identifier/<uuid>/clear-token (clear_device_token)
[2018-12-09][00:00:41][_][INFO] Outcome: Success
[2018-12-09][00:00:41][_][INFO] Response succeeded.
[2018-12-09][00:00:41][rocket::rocket][INFO] PUT /api/devices/identifier/abc/token application/json; charset=utf-8:
[2018-12-09][00:00:41][_][INFO] Matched: PUT /api/devices/identifier/<uuid>/token (put_device_token)
[2018-12-09][00:00:41][_][INFO] Outcome: Success
[2018-12-09][00:00:41][_][INFO] Response succeeded.

```

**Comment by TMHBOFH** [comment]
@dani-garcia
thanks for your fast help.
Now i get no error messages in server logs, but unfortunately the app crash after i enter the 2fa token(without any messages).
If i disable the 2fa it works fine.

Thanks for youre help

[2018-12-09][10:36:04][rocket::rocket][INFO] POST /api/accounts/prelogin application/json; charset=utf-8:
[2018-12-09][10:36:04][_][INFO] Matched: POST /api/accounts/prelogin (prelogin)
[2018-12-09][10:36:04][_][INFO] Outcome: Success
[2018-12-09][10:36:04][_][INFO] Response succeeded.
[2018-12-09][10:36:05][rocket::rocket][INFO] POST /identity/connect/token application/x-www-form-urlencoded:
[2018-12-09][10:36:05][_][INFO] Matched: POST /identity/connect/token (login)
[2018-12-09][10:36:05][_][INFO] Outcome: Success
[2018-12-09][10:36:05][_][INFO] Response succeeded.
[2018-12-09][10:36:20][rocket::rocket][INFO] POST /identity/connect/token application/x-www-form-urlencoded:
[2018-12-09][10:36:20][_][INFO] Matched: POST /identity/connect/token (login)
[2018-12-09][10:36:20][_][INFO] Outcome: Success
[2018-12-09][10:36:20][_][INFO] Response succeeded.

**Comment by i-ghost** [comment]
@TMHBOFH For me, the app only crashes the first time I enter 2FA. Entering it after the crash lets the app function normally.

Unfortunately I am also experiencing the sign out issue on the iOS app. Here are logs of when I tried opening the app, noticed I was signed out, then I signed in again:

```
2018-12-09T13:29:56.817814327Z POST /identity/connect/token application/x-www-form-urlencoded:
2018-12-09T13:29:56.817849928Z     => Matched: POST /identity/connect/token
2018-12-09T13:29:56.817867956Z POST /identity/connect/token application/x-www-form-urlencoded:
2018-12-09T13:29:56.817874427Z     => Matched: POST /identity/connect/token
2018-12-09T13:29:56.820979323Z ERROR: Failed to add device to user
2018-12-09T13:29:56.821259844Z     => Outcome: Success
2018-12-09T13:29:56.822066926Z     => Response succeeded.
2018-12-09T13:29:56.829135160Z     => Outcome: Success
2018-12-09T13:29:56.830349152Z     => Response succeeded.
2018-12-09T13:29:56.950377605Z PUT /api/devices/identifier/292777e2-03c2-43d1-8765-f3f3c7870506/token application/json; charset=utf-8:
2018-12-09T13:29:56.950441965Z     => Matched: PUT /api/devices/identifier/<uuid>/token
2018-12-09T13:29:56.952177153Z ERROR: Not implemented
2018-12-09T13:29:56.952196850Z     => Outcome: Success
2018-12-09T13:29:56.952203552Z     => Response succeeded.
2018-12-09T13:29:56.954593153Z PUT /api/devices/identifier/292777e2-03c2-43d1-8765-f3f3c7870506/clear-token:
2018-12-09T13:29:56.954644379Z     => Matched: PUT /api/devices/identifier/<uuid>/clear-token
2018-12-09T13:29:56.954653109Z     => Error: Content-Type is not JSON.
2018-12-09T13:29:56.954658766Z     => Outcome: Forward
2018-12-09T13:29:56.954664090Z     => Error: No matching routes for PUT /api/devices/identifier/292777e2-03c2-43d1-8765-f3f3c7870506/clear-token.
2018-12-09T13:29:56.954669768Z     => Warning: Responding with 404 Not Found catcher.
2018-12-09T13:29:56.954675096Z     => Response succeeded.
2018-12-09T13:30:25.357048253Z POST /api/accounts/prelogin application/json; charset=utf-8:
2018-12-09T13:30:25.357097700Z     => Matched: POST /api/accounts/prelogin
2018-12-09T13:30:25.357106419Z     => Outcome: Success
2018-12-09T13:30:25.357112409Z     => Response succeeded.
2018-12-09T13:30:25.530325234Z POST /identity/connect/token application/x-www-form-urlencoded:
2018-12-09T13:30:25.530369624Z     => Matched: POST /identity/connect/token
2018-12-09T13:30:25.608572688Z     => Outcome: Success
2018-12-09T13:30:25.609543223Z     => Response succeeded.
2018-12-09T13:30:25.785768335Z GET /api/accounts/profile application/json:
2018-12-09T13:30:25.786608583Z     => Matched: GET /api/accounts/profile
2018-12-09T13:30:25.788285193Z     => Outcome: Success
2018-12-09T13:30:25.788873756Z     => Response succeeded.
2018-12-09T13:30:26.094358685Z GET /api/sync application/json:
2018-12-09T13:30:26.094451541Z     => Matched: GET /api/sync
2018-12-09T13:30:26.096812120Z     => Outcome: Success
2018-12-09T13:30:26.097751646Z     => Response succeeded.
2018-12-09T13:30:26.167487270Z PUT /api/devices/identifier/292777e2-03c2-43d1-8765-f3f3c7870506/token application/json; charset=utf-8:
2018-12-09T13:30:26.167699116Z     => Matched: PUT /api/devices/identifier/<uuid>/token
2018-12-09T13:30:26.167821624Z ERROR: Not implemented
2018-12-09T13:30:26.167856045Z     => Outcome: Success
2018-12-09T13:30:26.167922278Z     => Response succeeded.
```

Note that this was using the `latest` tag, not `beta`. I suppose I should try `beta` again and report back.

**Comment by dani-garcia** [comment]
@quthla That `Failed to add device to user` is strange, I've added some more logging to the latest beta commit, hopefully that will give us more info.

@TMHBOFH The crashes happen to me too, on the latest ios app, I'll have to investigate more, though I'm not sure how it's happening.

@i-ghost The issues with the `token` and `clear-token` endpoints are fixed in the beta, but you are having the same issue as @quthla, so i'd like to now what your results would be running the latest beta.

@mprasil Can you trigger a new build, please?

**Comment by mprasil** [comment]
Build [triggered](https://hub.docker.com/r/mprasil/bitwarden/builds/b7akezhejaqjj5kko6eunuh/), give it about an hour.

A longer term update running latest beta from my side is, that logout issue didn't happen again after switching to beta couple days ago. (on Android)

**Comment by i-ghost** [comment]
Seems promising. Using the `beta` tag, I haven't used the app in over 12 hours but I've just tried it now and was logged in normally as expected - no forced signing out.

**Comment by i-ghost** [comment]
Ok, using the `beta` tag has definitely resolved the issue with being signed out, at least for me. The 2FA issue (iOS client crash) still persists, but I suspect that's an issue with the app itself. Disabling 2FA on my account works and lets me log in as normal. Not ideal, but it works.

**Comment by quthla** [comment]
Ok so after more than 2 days it happened again and now we know what's going on.

```
[2018-12-12][13:44:38][rocket::rocket][INFO] POST /identity/connect/token application/x-www-form-urlencoded:
[2018-12-12][13:44:38][_][INFO] Matched: POST /identity/connect/token (login)
[2018-12-12][13:44:38][rocket::rocket][INFO] POST /identity/connect/token application/x-www-form-urlencoded:
[2018-12-12][13:44:38][_][INFO] Matched: POST /identity/connect/token (login)
[2018-12-12][13:44:38][bitwarden_rs::api::identity][ERROR] Failed to add device to user: DatabaseError(
    __Unknown,
    "database is locked"
)
[2018-12-12][13:44:38][_][INFO] Outcome: Success
[2018-12-12][13:44:38][_][INFO] Response succeeded.
[2018-12-12][13:44:38][_][INFO] Outcome: Success
[2018-12-12][13:44:38][_][INFO] Response succeeded.
```

**Comment by dani-garcia** [comment]
It's a bit strange, why are there two login requests happening at the same time? It makes sense that the database is locked then, as there would be two connections trying to write to the same place at the same time.

I guess we could retry when there is an error in that case, we already do something similar for attachments, I think.

**Comment by quthla** [comment]
Was asking myself the same question. Guess there's some bug in the client. I just started the app as usual.

**Comment by quthla** [comment]
Thanks for all the support and quick reaction from you and mprasil.

Why are the Docker images built from mprasils repo rather than yours. The code is identical if I'm correct?

**Comment by mprasil** [comment]
The image is now [building](https://hub.docker.com/r/mprasil/bitwarden/builds/bcaqytdlgch25deb9saphty/).

@quthla, it's for historical reasons really. I've created the docker hub builds before they were official and a lot of people ended up using it, so we kept the `mprasil/bitwarden` docker hub repo there. I was also using my github fork, because there were some docker hub specific things I needed to have on top of this repo here. This has since been merged, but as far as I know there's no way to change the upstream git repository in docker hub.. But yeah they are identical now.

**Comment by quthla** [comment]
@mprasil Not sure but maybe this'll will help: https://github.com/docker/hub-feedback/issues/313#issuecomment-265843090

**Comment by mprasil** [comment]
Yeah, tried to follow that one, but it won't let me use repository other than mine.. Could be some permission on the GithHub side need to be set. But realistically it isn't that much of a burden the way it is now..

**Comment by dani-garcia** [comment]
The 2FA mobile crash should be fixed now with the latest master, and with that I think this can be closed now. If anyone has logout issues, please reopen the issue.
